stages:
- name: change directory
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: base-docker-image
      registry: 127.0.0.1:34557
timeout: 60
notification: {}
