name: Dockerfile validation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ghe-actions/dockerfile-validator@v1
      - name: Dockerfile Validator
        with:
          dockerfile: Dockerfile
          lint: dockerlint
          dockerlabelvalidate: yes
