name: Dockerfile validation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dockerfile Validator
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: Dockerfile
          lint: dockerlint
          dockerlabelvalidate: yes
